
version: '3.9'
services:
  opencamera:
    build: .
    image: opencamera:latest
    container_name: opencamera_con
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - type: bind
        source: $HOME/.Xauthority
        target: /root/.Xauthority.copy
      - ..:/ws
    network_mode: host